# Generated by Django 3.2.7 on 2021-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Doña', 'Doña'), ('Don', 'Don')], max_length=25, verbose_name='Título')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('status', models.CharField(max_length=25, verbose_name='Estado')),
                ('nationality', models.CharField(max_length=25, verbose_name='Nacionalidad')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('id_card', models.CharField(max_length=9, verbose_name='DNI')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('telephone', models.CharField(max_length=13, verbose_name='Teléfono')),
            ],
        ),
    ]
