# Generated by Django 3.2.7 on 2021-10-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('url', models.URLField(blank=True, null=True)),
                ('asking_price', models.FloatField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('expected_rent', models.FloatField(blank=True, default=0, null=True)),
                ('actual_rent', models.FloatField(blank=True, default=0, null=True)),
                ('width', models.FloatField(blank=True, default=0, null=True)),
                ('length', models.FloatField(blank=True, default=0, null=True)),
                ('community', models.FloatField(blank=True, default=0, null=True)),
                ('ibi', models.FloatField(blank=True, default=0, null=True)),
                ('purchase_tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tax.tax')),
                ('rent_tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tax.tax')),
            ],
        ),
    ]
