# Generated by Django 3.2.7 on 2021-10-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='real_estate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='real_estate.realestate'),
        ),
    ]
