# Generated by Django 3.2.7 on 2021-10-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_garage_real_estate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='garage',
            name='address',
        ),
        migrations.AddField(
            model_name='garage',
            name='floor',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Floor'),
        ),
        migrations.AddField(
            model_name='garage',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.parking'),
        ),
    ]
