# Generated by Django 3.2.7 on 2021-12-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('garage', '0003_auto_20211010_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.garage')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
    ]
